name: modpath_qa
channels:
  - conda-forge
  - defaults
dependencies:
  - flopy=3.2.9
  - geopandas=0.4.0=py_1
  - numpy=1.15.0
  - openpyxl=2.5.3
  - pandas=0.23.3
  - pyshp=1.2.12
  - python=3.6.5
  - pip
